### ISSUE TITLE
Remove invisible banner obstructing e.g. the "file upload" button

### ISSUE THREAD

**Issue by dumblob** [stonecrusher/stylus-UserCSS#12]
There is a banner at the bottom of the "compose new email" & "email listing" (and possibly other) pages which obstructs e.g. buttons for "file upload" etc. The following fixes it if put into `https?:\/\/((mm|3c|3c-bap|adressbook|account|cloud|kalender|wusa|metasearch|(.+\.)?navigator)\.)?web\.de\/.*` section.

```css
    /* the invisible overlay protection at the message bottom */
    #superbanner { display: none !important; }
```

This applies to all devices, but is easier to reproduce on low-resolution devices.

## Screenshot(s)
N/A

## Additional information
- Operating System: Arch Linux
- Browser + version:  Chromium 91.0
- CSS extension + version: Stylus 1.5.6
