### ISSUE TITLE
Support low-width devices (especially tablets) again

### ISSUE THREAD

**Issue by dumblob** [stonecrusher/stylus-UserCSS#7]
Could the [support for tablets](https://github.com/stonecrusher/stylus-UserCSS/commit/55e306d01d84ece2173148af6a00190936d37f1a#diff-0b7515660c5490de0448c3609f2c20eeL344 ) in **web.de mailbox** be restored? I've now tried different combinations of the old code and I found out it's not any more needed and only one addition is necessary:

```css
/* prefer line wraps over horizontal scrolling of the whole page on narrow devices like tablets */
.page { min-width: auto; }
```

Just put it anywhere under the regex `https?:\/\/((mm|3c|3c-bap|adressbook|account|cloud|kalender|wusa|metasearch|(.+\.)?navigator)\.)?web\.de\/.*`.

I think it doesn't need to be optional in the plugin settings any more. Because it's "auto" and thus shouldn't do any harm to anyone nor impose any maintenance burden.
